### PR TITLE
[ZH] Translation Request

### PR DESCRIPTION
**Pull request by dchenmei**
#16 Added Chinese translation

### CODE REVIEW

**Comment by felipemarinho97** [comment]
Thank you for the contribution @dchenmei ! Please remember to also import moment.js Chinese locale.

**Comment by dchenmei** [comment]
@felipemarinho97 Thanks for catching that, should okay now.

**Comment by felipemarinho97** [comment]
@dchenmei Can you provide the region of your chinese? CN, HK or TW?

**Comment by dchenmei** [comment]
@felipemarinho97 I wrote it in standard/common Chinese, so CN.

**Pull request merged**
